services:
  - type: web
    name: shahrukh-auto-care
    runtime: docker
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: DATABASE_HOST
        fromDatabase:
          name: shahrukh-auto-care-db
          property: host

      - key: DATABASE_PORT
        fromDatabase:
          name: shahrukh-auto-care-db
          property: port

      - key: DATABASE_NAME
        fromDatabase:
          name: shahrukh-auto-care-db
          property: database

      - key: DATABASE_USERNAME
        fromDatabase:
          name: shahrukh-auto-care-db
          property: user

      - key: DATABASE_PASSWORD
        fromDatabase:
          name: shahrukh-auto-care-db
          property: password

      - key: DATABASE_DRIVER
        value: org.postgresql.Driver

databases:
  - name: shahrukh-auto-care-db
    plan: free
